### ISSUE TITLE
Issue With URI Parse and Null Safety

### ISSUE THREAD

**Issue by ujjwalsittu** [nikhiladmin/mapmyindia-flutter#1]
There is issue with Null Safety and URI Parse
![image](https://user-images.githubusercontent.com/26293424/116468484-88dded00-a88e-11eb-9904-c88ba00bbe33.png)

![image](https://user-images.githubusercontent.com/26293424/116468448-7cf22b00-a88e-11eb-8f19-35bb6a3e60aa.png)

**Comment by nikhiladmin** [comment]
hello @ujjwalsittu
Sorry for inconvenience this issue has been fixed please upgrade package version to `^1.0.7` .
